export const teams = [
  { id: 1, name: "Royal Strikers", short: "RS", color: "#e63946", logo: "🦁", wins: 8, losses: 2, nrr: "+1.234", points: 16 },
  { id: 2, name: "Thunder Kings", short: "TK", color: "#2196F3", logo: "⚡", wins: 7, losses: 3, nrr: "+0.876", points: 14 },
  { id: 3, name: "Golden Eagles", short: "GE", color: "#FF9800", logo: "🦅", wins: 6, losses: 4, nrr: "+0.543", points: 12 },
  { id: 4, name: "Storm Warriors", short: "SW", color: "#9C27B0", logo: "🌩️", wins: 5, losses: 5, nrr: "+0.102", points: 10 },
  { id: 5, name: "Iron Knights", short: "IK", color: "#607D8B", logo: "⚔️", wins: 4, losses: 6, nrr: "-0.215", points: 8 },
  { id: 6, name: "Blaze Panthers", short: "BP", color: "#FF5722", logo: "🐆", wins: 3, losses: 7, nrr: "-0.678", points: 6 },
  { id: 7, name: "Silver Wolves", short: "SW2", color: "#78909C", logo: "🐺", wins: 2, losses: 8, nrr: "-1.023", points: 4 },
  { id: 8, name: "Venom Cobras", short: "VC", color: "#4CAF50", logo: "🐍", wins: 1, losses: 9, nrr: "-1.839", points: 2 },
];

export const matches = [
  {
    id: 1,
    team1: "Royal Strikers",
    team2: "Thunder Kings",
    team1Short: "RS",
    team2Short: "TK",
    date: "24 Jun 2026",
    time: "7:30 PM",
    venue: "Eden Gardens, Kolkata",
    status: "live",
    team1Score: "187/4 (16.2)",
    team2Score: "142/3 (14.0)",
    team1Color: "#e63946",
    team2Color: "#2196F3",
  },
  {
    id: 2,
    team1: "Golden Eagles",
    team2: "Storm Warriors",
    team1Short: "GE",
    team2Short: "SW",
    date: "25 Jun 2026",
    time: "3:30 PM",
    venue: "Wankhede Stadium, Mumbai",
    status: "upcoming",
    team1Score: null,
    team2Score: null,
    team1Color: "#FF9800",
    team2Color: "#9C27B0",
  },
  {
    id: 3,
    team1: "Iron Knights",
    team2: "Blaze Panthers",
    team1Short: "IK",
    team2Short: "BP",
    date: "25 Jun 2026",
    time: "7:30 PM",
    venue: "Chinnaswamy Stadium, Bengaluru",
    status: "upcoming",
    team1Score: null,
    team2Score: null,
    team1Color: "#607D8B",
    team2Color: "#FF5722",
  },
  {
    id: 4,
    team1: "Thunder Kings",
    team2: "Golden Eagles",
    team1Short: "TK",
    team2Short: "GE",
    date: "23 Jun 2026",
    time: "7:30 PM",
    venue: "M.A. Chidambaram Stadium, Chennai",
    status: "completed",
    team1Score: "210/6 (20.0)",
    team2Score: "198/8 (20.0)",
    winner: "Thunder Kings",
    team1Color: "#2196F3",
    team2Color: "#FF9800",
  },
  {
    id: 5,
    team1: "Silver Wolves",
    team2: "Venom Cobras",
    team1Short: "SW2",
    team2Short: "VC",
    date: "22 Jun 2026",
    time: "3:30 PM",
    venue: "Rajiv Gandhi Stadium, Hyderabad",
    status: "completed",
    team1Score: "155/9 (20.0)",
    team2Score: "134/10 (18.4)",
    winner: "Silver Wolves",
    team1Color: "#78909C",
    team2Color: "#4CAF50",
  },
  {
    id: 6,
    team1: "Royal Strikers",
    team2: "Iron Knights",
    team1Short: "RS",
    team2Short: "IK",
    date: "26 Jun 2026",
    time: "7:30 PM",
    venue: "Narendra Modi Stadium, Ahmedabad",
    status: "upcoming",
    team1Score: null,
    team2Score: null,
    team1Color: "#e63946",
    team2Color: "#607D8B",
  },
];

export const topPlayers = [
  { rank: 1, name: "Virat Mehta", team: "Royal Strikers", role: "Batsman", runs: 542, avg: 67.75, sr: 148.6, color: "#e63946" },
  { rank: 2, name: "Rohit Sharma Jr.", team: "Thunder Kings", role: "Batsman", runs: 498, avg: 55.3, sr: 142.0, color: "#2196F3" },
  { rank: 3, name: "Suresh Nair", team: "Golden Eagles", role: "All-rounder", runs: 421, avg: 46.8, sr: 138.5, color: "#FF9800" },
  { rank: 4, name: "Aakash Patel", team: "Storm Warriors", role: "Batsman", runs: 387, avg: 43.0, sr: 135.2, color: "#9C27B0" },
  { rank: 5, name: "Dev Kumar", team: "Iron Knights", role: "Batsman", runs: 356, avg: 39.5, sr: 130.1, color: "#607D8B" },
];

export const topBowlers = [
  { rank: 1, name: "Jasprit Roy", team: "Thunder Kings", role: "Bowler", wickets: 18, economy: 6.8, avg: 14.2, color: "#2196F3" },
  { rank: 2, name: "Mohammed Ali", team: "Royal Strikers", role: "Bowler", wickets: 16, economy: 7.1, avg: 16.5, color: "#e63946" },
  { rank: 3, name: "Ravi Shankar", team: "Blaze Panthers", role: "Bowler", wickets: 14, economy: 7.4, avg: 18.3, color: "#FF5722" },
  { rank: 4, name: "Arjun Das", team: "Storm Warriors", role: "Bowler", wickets: 13, economy: 7.6, avg: 19.1, color: "#9C27B0" },
  { rank: 5, name: "Prateek Singh", team: "Silver Wolves", role: "Bowler", wickets: 12, economy: 8.0, avg: 21.4, color: "#78909C" },
];
